name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            server/package-lock.json
            client/package-lock.json

      - name: Install dependencies (workspaces)
        run: npm ci

      - name: Type check - server
        run: npm run -w server type-check || true

      - name: Type check - client
        run: npm run -w client type-check

      - name: Run tests - server only
        run: npm run -w server test --

      - name: Build client
        run: npm run -w client build